Bigquery refactor
tuva-health/pmpm pull request #6
Opened 2022-12-21 15:55 UTC by tuvaforrest

## Describe your changes
updated a couple things to support bigquery

## How has this been tested?
ran on redshift, bigquery, and snowflake

## Reviewer focus
Run on each if you like.  Let me know if you think the new macro for date_part is good or if we should cast the output natively or 

## Checklist before requesting a review
- [x]  I have recorded a Loom performing a self-review of my code
- [x]  My code follows style guidelines
- [x]  I have commented my code as necessary
- [x]  I have testing by code by running `dbt build` in the following warehouse(s):
    - [x]  Snowflake
    - [x]  Redshift
    - [x]  Bigquery
- [x]  I have implemented generic dbt tests to validate primary keys/uniqueness in my model
- [x]  I have updated dbt docs by running `dbt docs generate` and copying the appropriate files to the `docs/` path
- [x]  I have added at least one Github label to this PR

## (Optional) Gif of how this PR makes you feel
![gif](https://media.giphy.com/media/xQ8S8HYQQLw76/giphy.gif)

(because the panda is big!)

## Loom link

Note, since I recorded the loom I made a few small change: I added Bigquery to the readme, updated the version number in the dbt_project.yml to reflect the next release, and removed trailing whitespace in the variables that may have been causing an issue in another package for a customer (though I CNR).

https://www.loom.com/share/2eafb2d345f24a72be293d6dbb976f37

## For reviewers:
[Best practices for reviewing pull requests.](https://www.notion.so/Pull-Request-Review-Best-Practices-b486354d76c04982889f2178fe777c1c)

2022-12-21 16:03 UTC, aneiderhiser approved these changes

2023-01-03 19:37 UTC, thutuva requested changes
Just need the package version updated in the ReadMe.

I also tested in BQ, redshift, and PMPM since my CI was not ready for this PR.

2023-01-03 19:37 UTC, thutuva commented on README.md
The release version in the ReadMe needs to be updated.

(I couldn't make a comment there since my GitHub is only showing diffs)

2023-01-04 15:27 UTC, tuvaforrest commented on README.md
updated

2023-01-04 15:42 UTC, thutuva approved these changes
All set, thanks!

2023-01-04 15:42 UTC, merged